---
title: "20210911-figures-2"
author: "Min Yang"
date: "9/11/2021"
output: html_documentx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#空间zone3的所有细胞分布
load("20210818-spatial/B6-bin50-spatial-phago-map.RData")
zone3.spatial.color <- c(rep("#E7E7E7", 2), "#FB8072", rep("#E7E7E7", 6), "#E7E7E7", "#B2DF8A", "#E7E7E7", "#CAB2D6", 
                         rep("#E7E7E7", 2), "#6A3D9A", rep("#E7E7E7", 15))
pdf("20210827-figures/figure4/Figure4-4-zone3-B6.pdf", width = 10, height = 9)
ggplot() + 
  geom_point(B6.bin50.celltype.df, mapping = aes(x = -x, y = -y, color = cell_type), size = 1.3) +
  scale_color_manual(values = zone3.spatial.color) + 
  theme_classic() + 
  theme(axis.text = element_blank())
dev.off()
```

```{r}
#Immune 分析
load("../20210201-integrate/UE-immune-hamrony-rename.RData")
DimPlot(UE.immune.harmony, label = T)
UE.immune.harmony.markers <- FindAllMarkers(UE.immune.harmony, min.pct = 0.5, logfc.threshold = 0.5, only.pos = T)
write.table(UE.immune.harmony.markers, file = "20210827-figures/files/UE-immune-harmony-markers.csv", sep = ",", quote = F)
UE.immune.harmony.markers.top20 <- UE.immune.harmony.markers %>% group_by(cluster) %>% top_n(n = 20, avg_logFC)
write.table(UE.immune.harmony.markers.top20, file = "20210827-figures/files/UE-immune-harmony-markers-top20.csv", sep = ",", quote = F)
UE.immune.harmony.markers.top5 <- UE.immune.harmony.markers %>% group_by(cluster) %>% top_n(n = 5, avg_logFC)
pdf("20210827-figures/figure4/Figure4-1-immune-top5-dotplot.pdf", width = 18, height = 6)
DotPlot(UE.immune.harmony, features = unique(UE.immune.harmony.markers.top5$gene), cols = "Spectral") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1))
dev.off()
pdf("20210827-figures/figure4/Figure4-1-immune-top5-featureplot-1.pdf", width = 10, height = 5)
FeaturePlot(UE.immune.harmony, features = c("tdTomato", "Ptprc"), pt.size = 0.5, ncol = 2) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))
dev.off()

immune.color <- c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#2E8B57", "#CAB2D6", "#FF7F00", "#FDBF6F", "#6A3D9A")
UE.immune.harmony.count <- data.frame(table(UE.immune.harmony$time, UE.immune.harmony$cellname), check.names = F)
#UE.immune.harmony.count$Var2 <- factor(UE.immune.harmony.count$Var2, levels = immune.levels)
pdf("20210827-figures/figure4/Figure4-1-immune-proportion.pdf", width = 10, height = 9)
ggplot() + 
  geom_bar(UE.immune.harmony.count, mapping = aes(x = Var1, y = Freq, fill = Var2), stat = "identity", position = "fill") + 
  scale_fill_manual(values = immune.color) + 
  theme(panel.background = element_rect(color = "black", fill = "white", size = 1),
        panel.grid = element_blank(),
        axis.line = element_blank()) + 
  labs(title = "Immune cells proportion")
dev.off()
#计算每种免疫细胞类型在时间点所有细胞的比例
UE.harmony.pc30$tdTomato <- UE.harmony.pc30@assays$RNA@counts["tdTomato", ]>0
UE.harmony.pc30.tdTomato.neg <- subset(UE.harmony.pc30, subset = tdTomato == FALSE)
total.count <- table(UE.harmony.pc30.tdTomato.neg$time)#注意排序到5.5 -> 10.5
UE.immune.harmony.count.ratio <- data.frame(apply(table(UE.immune.harmony$time, UE.immune.harmony$cellname), 2, function(x){x/total.count * 100}), check.names = F)
UE.immune.harmony.count.ratio$time <- rownames(UE.immune.harmony.count.ratio)
UE.immune.harmony.count.ratio <- melt(UE.immune.harmony.count.ratio, id.vars = "time")
UE.immune.harmony.count.ratio$time <- factor(UE.immune.harmony.count.ratio$time, levels = c("T55", "T65", "T75", "T85", "T95", "T105"))
pdf("20210827-figures/figure4/Figure4-1-immune-proportion-dodge.pdf", width = 10, height = 9)
ggplot() + 
  geom_bar(UE.immune.harmony.count.ratio, mapping = aes(x = variable, y = value, fill = time), stat = "identity", position = "dodge") + 
  scale_fill_manual(values = time.color) + 
  theme(panel.background = element_rect(color = "black", fill = "white", size = 1),
        panel.grid = element_blank(),
        axis.line = element_blank()) + 
  labs(title = "Immune cells proportion")
dev.off()
pdf("20210827-figures/figure4/Figure4-1-immune-proportion-facet.pdf", width = 10, height = 9)
ggplot() + 
  geom_bar(UE.immune.harmony.count.ratio, mapping = aes(x = variable, y = value, fill = time), stat = "identity", position = "dodge") + 
  scale_fill_manual(values = time.color) + 
  facet_wrap(~ variable, scales = "free") + 
  theme(panel.background = element_rect(color = "black", fill = "white", size = 1),
        panel.grid = element_blank(),
        axis.line = element_blank()) + 
  labs(title = "Immune cells proportion")
dev.off()
#FB-immune 的基因点亮图
pdf("20210827-figures/figure5/Figure5-FB-imune-Ptprc-Des-featureplot.pdf", width = 15, height = 15)
FeaturePlot(UE.immune.harmony, features = c("Ptprc", "Des", "Hand2", "Dcn", "Pgr", "Col1a1", "Col3a1", "Ptn"), ncol = 3, pt.size = 0.5) & 
  scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))
dev.off()
#FB-immune在空间上的定位
B6.color <- c(rep("#E7E7E7", 15), immune.color[10], rep("#E7E7E7", 15))
pdf("20210827-figures/figure5/Figure5-B6-bin50-FB-immune.pdf", width = 10, height = 9)
ggplot() + 
  geom_point(B6.bin50.celltype.df, mapping = aes(x = -x, y = -y, color = cell_type), size = 1.3) +
  scale_color_manual(values = B6.color) + 
  theme_classic() + 
  theme(axis.text = element_blank())
dev.off()
#tdTomato+ 与tdTomato- Mac 的比较
Mac <- subset(UE.immune.harmony, subset = cellname %in% "Pro-Mac")
Mac$tdTomato <- Mac@assays$RNA@data["tdTomato", ]>0
Mac@active.ident <- factor(Mac$tdTomatfigure4o)
Mac.markers <- FindAllMarkers(Mac, min.pct = 0.5, logfc.threshold = 0.5, only.pos = T)
Mac.avg <- AverageExpression(Mac)
Mac.avg <- Mac.avg$RNA
colnames(Mac.avg)[1:2] <- c("negtive", "positive")
Mac.avg$gene <- rownames(Mac.avg)
Mac.avg.markers <- merge(Mac.avg, Mac.markers, by = "gene", all = F)
pdf("20210827-figures/figure4/Figure4-2-tdTomato-compare-scatter-label.pdf", width = 6, height = 5)
ggplot() + 
  geom_point(Mac.avg, mapping = aes(x = log2(positive + 1), y = log2(negtive + 1)), color = "lightgray", size = 1.3) + 
  geom_point(Mac.avg.markers, mapping = aes(x = log2(positive + 1), y = log2(negtive + 1), color = cluster), size = 1.6) + 
  scale_color_manual(values = c("darkblue", "darkred")) + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white")) + 
  annotate("text", x = log2(Mac.avg.markers$positive+1), y = log2(Mac.avg.markers$negtive+1), label = Mac.avg.markers$gene)
dev.off()

#FB-immune vs DSC
FB.immune <- subset(UE.immune.harmony, subset = cellname == "FB-immune")
UE.FB <- merge(FB.immune, UE.decidual)
UE.FB$compare <- gsub(".*-", "", UE.FB@active.ident)
UE.FB@active.ident <- factor(UE.FB$compare, levels = c("D", "immune"))
UE.FB.avg <- AverageExpression(UE.FB)
UE.FB.avg <- UE.FB.avg$RNA
UE.FB.avg$gene <- rownames(UE.FB.avg)
UE.FB.markers <- FindAllMarkers(UE.FB, only.pos = T, min.pct = 0.5, logfc.threshold = 0.5)
write.table(UE.FB.markers, file = "20210827-figures/files/iDSC-compare-DSC-DEGs.csv", sep = ",", row.names = F)
UE.FB.avg.markers <- merge(UE.FB.avg, UE.FB.markers, by = "gene")
pdf("20210827-figures/figure4/Figure4-3-FB-immune-DSC-compare-scatter-label.pdf", width = 6, height = 5)
ggplot() + 
  geom_point(UE.FB.avg, mapping = aes(x = log2(D + 1), y = log2(immune + 1)), color = "lightgray", size = 1.3) + 
  geom_point(UE.FB.avg.markers, mapping = aes(x = log2(D + 1), y = log2(immune + 1), color = cluster), size = 1.6) + 
  scale_color_manual(values = c("#5F9EA0", "#6A3D9A")) + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white")) + 
  annotate("text", x = log2(UE.FB.avg.markers$D + 1), y = log2(UE.FB.avg.markers$immune + 1), label = UE.FB.avg.markers$gene)
dev.off()
enrich.GO.function <- function(geneset){
  enrich.GO <- enrichGO(gene = geneset,
                        OrgDb = "org.Mm.eg.db",
                        keyType = "SYMBOL",
                        ont = "BP",
                        pAdjustMethod = "BH",
                        pvalueCutoff = 0.05)
  enrich.GO <- simplify(enrich.GO, cutoff = 0.6, by = "p.adjust", select_fun = min)
  enrich.GO <- enrich.GO@result[enrich.GO@result$pvalue<0.01, ]
  return(enrich.GO)
}
UE.FB.enrich.GO <- enrich.GO.function(UE.FB.markers[UE.FB.markers$cluster == "immune", ]$gene)
UE.FB.enrich.GO <- UE.FB.enrich.GO[1:10, ]
UE.FB.enrich.GO$Description <- factor(UE.FB.enrich.GO$Description, 
                                      levels = UE.FB.enrich.GO[rev(order(UE.FB.enrich.GO$pvalue)), ]$Description)
write.table(UE.FB.enrich.GO, file = "20210827-figures/files/iDSC-compare-DSC-DEGs-GO-20230514.txt", sep = "\t", row.names = F)
pdf("20210827-figures/figure4/Figure4-3-FB-immune-DSC-compare-GO-20230514.pdf")
ggplot() + 
  geom_bar(UE.FB.enrich.GO, mapping = aes(x = -log10(pvalue), y = Description), stat = "identity") + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white"))
dev.off()
```

```{r}
#讨论Cycling DSC, FB-immune, NK, Mac/Pro-Mac之间的相互作用
load("../20210201-integrate/UE-harmony-cellchat-subname-results-20210903.RData")
df.net <- subsetCommunication(UE.harmony.cellchat, slot.name = 'netP')
df.net$paires_cell <- paste(df.net$source, df.net$target, sep = '_')
zone3.inter <- c("Top2a-D_Pro-Mac", "Top2a-D_NK", "Top2a-D_FB-immune",
                 "Pro-Mac_Top2a-D", "Pro-Mac_NK", "Pro-Mac_FB-immune",
                 "NK_Top2a-D", "NK_Pro-Mac", "NK_FB-immune", 
                 "FB-immune_Top2a-D", "FB-immune_Pro-Mac", "FB-immune_NK")
df.net.zone3 <- df.net[df.net$paires_cell %in% c(zone3.inter), ]
df.net.zone3$paires_cell <- factor(df.net.zone3$paires_cell, levels = zone3.inter)
#df.net.zone3.top5$order <- paste(df.net.zone3.top5$source, df.net.zone3.top5$target, sep = ' ')
#df.net.zone3.top5 <- df.net.zone3 %>% group_by(paires_cell) %>% top_n(n = 5, prob)
pdf("20210827-figures/figure4/Figure4-3-zone3-cellchat-pathway-dotplot.pdf", width = 8, height = 8)
ggplot() + 
  geom_point(df.net.zone3, mapping = aes(x = paires_cell, y = pathway_name, color = prob, size = -pval)) +
  scale_color_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1))
dev.off()
pdf("20210827-figures/figure4/Figure4-3-zone3-cellchat-LR-dotplot.pdf", width = 10, height = 14)
netVisual_bubble(UE.harmony.cellchat, sources.use = c(4,18,12,16), targets.use = c(4,18,12,16), remove.isolate = FALSE)
dev.off()
```
#将cell cycle的再细分, 直接使用cell cycle基因进行分群
```{r}
library("harmony")
s.genes <- str_to_title(cc.genes$s.genes)
g2m.genes <- str_to_title(cc.genes$g2m.genes)
cycle.gene <- c(s.genes, g2m.genes)
decidual.cycle <- subset(UE.decidual, subset = cellname == "Top2a-D")
decidual.cycle <- FindVariableFeatures(decidual.cycle, selection.method = "vst", nfeatures = 2000)
decidual.cycle$CC.Score <- decidual.cycle$S.Score - decidual.cycle$G2M.Score
decidual.cycle <- ScaleData(decidual.cycle, features = rownames(decidual.cycle))
decidual.cycle <- RunPCA(decidual.cycle, features = cycle.gene)
#decidual.cycle <- RunHarmony(decidual.cycle, "time", plot_convergence = TRUE, reduction = "pca")
DimPlot(object = decidual.cycle, reduction = "harmony", pt.size = .1, group.by = "time")
ElbowPlot(decidual.cycle, ndims = 80, reduction = "pca")
decidual.cycle <- RunUMAP(decidual.cycle, reduction = "pca", dims = 1:10)
decidual.cycle <- FindNeighbors(decidual.cycle, reduction = "pca", dims = 1:10)
decidual.cycle <- FindClusters(decidual.cycle, resolution = 0.2)
DimPlot(decidual.cycle)
save(decidual.cycle, file = "../20210201-integrate/UE-DSC-cycling-subclusters.RData")
decidual.cycle.markers <- FindAllMarkers(decidual.cycle, min.pct = 0.5, logfc.threshold = 0.25, only.pos = T)
decidual.cycle.markers.top10 <- decidual.cycle.markers %>% group_by(cluster) %>% top_n(n = 10, avg_logFC)
DoHeatmap(decidual.cycle, features = decidual.cycle.markers.top10$gene)
```

```{r}
load("20210818-spatial/B6-bin50-spatial-phago-map.RData")
B6.bin50.celltype.score <- GetAssayData(B6.bin50, slot = "data")
B6.bin50.celltype.max <- apply(B6.bin50.celltype.score, 2, function(x) rownames(B6.bin50.celltype.score)[which.max(x)])
B6.bin50.celltype.df <- data.frame(cell_type = B6.bin50.celltype.max, 
                                cell_name = names(B6.bin50.celltype.max), 
                                GetTissueCoordinates(B6.bin50), 
                                nFeature_RNA = B6.bin50$nFeature_Spatial, 
                                nCount_RNA = B6.bin50$nCount_Spatial)
B6.cell_type.levels <- c(decidual.levels[1:8], immune.levels[c(1:4,7:10)], EC.levels[1:4], major.levels[4:5], major.levels[7:11], tropho.levels[c(1,3:5)])
B6.bin50.celltype.df$cell_type <- factor(B6.bin50.celltype.df$cell_type, levels = B6.cell_type.levels)
B6.color <- c(decidual.color[1:8], immune.color[c(1:3,4,7:10)], EC.color[1:4], major.color[c(4,5,7:11)], tropho.color[c(1,3:5)])
NK <- B6.bin50.celltype.df[B6.bin50.celltype.df$cell_type == "NK", ]
ggplot() + 
  geom_point(B6.bin50.celltype.df, mapping = aes(x = -x, y = -y, color = cell_type), size = 1.3) +
  scale_color_manual(values = B6.color) + 
  annotate("text", x = -NK$x, y = -NK$y, label = NK$cell_name, size = 2) + 
  theme_classic() + 
  theme(axis.text = element_blank())
```


```{r}
#做FB-immune在cluster3和cluster6中的比较
load("20210818-spatial/B6-bin50-spatial-phago-map.RData")
B6.bin50$cluster_celltype <- paste(B6.bin50$seurat_clusters, B6.bin50$celltype, sep = "_")
DefaultAssay(B6.bin50) <- "SCT"
B6.bin50@active.ident <- factor(B6.bin50$cluster_celltype)
B6.bin50.cluster.celltype.avg <- AverageExpression(B6.bin50, assays = "SCT")
#通路中ligend的基因比较
#load cluster3和cluster6的pathway结果
B6.cluster3.cell.interaction <- read.table("20210827-figures/figure4/B6-spatial-cluster3-interaction-average.csv", sep = ",", header = T, check.names = F)
B6.cluster6.cell.interaction <- read.table("20210827-figures/figure4/B6-spatial-cluster6-interaction-average.csv", sep = ",", header = T, check.names = F)
#这里注意问题，receptor有两个的只保留了第一个
spatial_clusters <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"))
spatial_clusters <- spatial_clusters[c(2,3,4,5,8,10,14,12,11,16,17)]
FB.immune.cluster3.6 <- B6.bin50.cluster.celltype.avg$SCT[, c("3_FB-immune", "6_FB-immune")]
FB.immune.cluster3.6.ligend <- FB.immune.cluster3.6[as.character(unique(B6.spatial.cluster6.LR$ligend_gene)), ]
FB.immune.cluster3.6.ligend$ligend.gene <- rownames(FB.immune.cluster3.6.ligend)
FB.immune.cluster3.6.ligend <- melt(FB.immune.cluster3.6.ligend, id.vars = "ligend.gene")
pdf("20210827-figures/figure4/Figure4-11-FB-immune-cluster3-6-ligend-compare.pdf", width = 10, height = 8)
ggplot() +
  geom_bar(FB.immune.cluster3.6.ligend, mapping = aes(x = value, y = ligend.gene, fill = variable), stat = "identity", position = "dodge") + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white")) + 
  scale_fill_manual(values = c(spatial_clusters[c(4,7)]))
dev.off()
#计算cluster3，6中所有FB-immune为ligend的pathway的表达
B6.cluster3.cell.interaction.FB <- B6.cluster3.cell.interaction[B6.cluster3.cell.interaction$Ligend == "FB-immune" |  
                                                                 B6.cluster3.cell.interaction$Receptor == "FB-immune", ]
B6.cluster3.cell.interaction.FB <- aggregate(B6.cluster3.cell.interaction.FB$x, list(B6.cluster3.cell.interaction.FB$L_R), sum)
colnames(B6.cluster3.cell.interaction.FB) <- c("signal", "cluster3")
B6.cluster6.cell.interaction.FB <- B6.cluster6.cell.interaction[B6.cluster6.cell.interaction$Ligend == "FB-immune" |  
                                                                 B6.cluster6.cell.interaction$Receptor == "FB-immune", ]
B6.cluster6.cell.interaction.FB <- aggregate(B6.cluster6.cell.interaction.FB$x, list(B6.cluster6.cell.interaction.FB$L_R), sum)
colnames(B6.cluster6.cell.interaction.FB) <- c("signal", "cluster6")
B6.cluster36.cell.interaction.FB <- merge(B6.cluster3.cell.interaction.FB, B6.cluster6.cell.interaction.FB, by = "signal", all = T)
B6.cluster36.cell.interaction.FB[is.na(B6.cluster36.cell.interaction.FB)] <- 0
B6.cluster36.cell.interaction.FB <- melt(B6.cluster36.cell.interaction.FB, id.vars = "signal")
pdf("20210827-figures/figure4/Figure4-11-FB-immune-cluster3-6-sigal-compare.pdf", width = 10, height = 10)
ggplot() +
  geom_bar(B6.cluster36.cell.interaction.FB, mapping = aes(x = value, y = signal, fill = variable), stat = "identity", position = "dodge") + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white")) + 
  scale_fill_manual(values = c(spatial_clusters[c(4,7)]))
dev.off()

#比较FB-immune在cluster3和cluster6中的差异
UE.FB.cluster3.6.markers <- FindMarkers(B6.bin50, ident.1 = "3_FB-immune", ident.2 = "6_FB-immune", only.pos = F, min.pct = 0.5, logfc.threshold = 0.5)
UE.FB.cluster3.6.markers$gene <- rownames(UE.FB.cluster3.6.markers)
UE.FB.cluster3.6.markers$color <- 1
UE.FB.cluster3.6.markers[UE.FB.cluster3.6.markers$avg_logFC<0, ]$color <- -1
UE.FB.cluster3.6.markers$color <- factor(UE.FB.cluster3.6.markers$color, levels = c(1, -1))
FB.immune.cluster3.6$gene <- rownames(FB.immune.cluster3.6)
UE.FB.cluster3.6.markers <- merge(UE.FB.cluster3.6.markers, FB.immune.cluster3.6, all.x = T)
UE.FB.cluster3.6.markers.top10 <- UE.FB.cluster3.6.markers %>% group_by(color) %>% top_n(n = 10, avg_logFC)
UE.FB.cluster3.6.markers.top10 <- UE.FB.cluster3.6.markers.top10[rev(order(UE.FB.cluster3.6.markers.top10$avg_logFC)), ]
B6.bin50.FB.cluster3.6 <- subset(B6.bin50, subset = cluster_celltype %in% c("3_FB-immune", "6_FB-immune"))
B6.bin50.FB.cluster3.6$active.ident <- B6.bin50.FB.cluster3.6@active.ident
pdf("20210827-figures/figure4/Figure4-11-FB-immune-cluster3-6-top10-violin-trNK.pdf", height = 25, width = 6)
StackedVlnPlot(B6.bin50.FB.cluster3.6, features = UE.FB.cluster3.6.markers.top10$gene, cols = spatial_clusters[c(4,7)])
dev.off()
B6.bin50.FB.immune <- subset(B6.bin50, subset = cluster_celltype %in% c("3_FB-immune", "6_FB-immune"))
B6.bin50.FB.immune <- ScaleData(B6.bin50.FB.immune, features = rownames(B6.bin50.FB.immune))
B6.bin50.FB.immune.markers <- FindAllMarkers(B6.bin50.FB.immune, min.pct = 0.5, logfc.threshold = 0.5, only.pos = T)
pdf("20210827-figures/figure4/Figure4-11-FB-immune-cluster3-6-DEGs-heatmap.pdf", height = 20, width = 8)
DoHeatmap(B6.bin50.FB.immune, features = B6.bin50.FB.immune.markers$gene) + 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 5, name = "RdBu")))
dev.off()

ggplot() + 
  geom_point(FB.immune.cluster3.6, mapping = aes(x = log2(`3_FB-immune` + 1), y = log2(`6_FB-immune` + 1)), color = "lightgray", size = 1.3) + 
  geom_point(UE.FB.cluster3.6.markers, mapping = aes(x = log2(`3_FB-immune` + 1), y = log2(`6_FB-immune` + 1), color = color), size = 1.6) + 
  scale_color_manual(values = spatial_clusters[c(4,7)]) + 
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white")) + 
  annotate("text", x = log2(UE.FB.cluster3.6.markers$`3_FB-immune` + 1), y = log2(UE.FB.cluster3.6.markers$`6_FB-immune` + 1), label = UE.FB.cluster3.6.markers$gene)
dev.off()
B6.bin50.FB.immune <- subset(B6.bin50, subset = cluster_celltype %in% c("3_FB-immune", "6_FB-immune"))
DefaultAssay(B6.bin50.FB.immune) <- "SCT"
```

```{r 比较cluster0，1，3，6中的cell-cell interaction的差别，整体的，未过滤的}
B6.spatial.cluster0.LR <- read.table("20210827-figures/figure4/B6-spatial-cluster0-LR.csv", sep = ",", header = T)
cluster0.LR.agg <- aggregate(B6.spatial.cluster0.LR$expr, by = list(B6.spatial.cluster0.LR$interaction_name), sum)
cluster0.LR.agg$x <- cluster0.LR.agg$x/length(cluster0.LR.agg$Group.1)
B6.spatial.cluster1.LR <- read.table("20210827-figures/figure4/B6-spatial-cluster1-LR.csv", sep = ",", header = T)
cluster1.LR.agg <- aggregate(B6.spatial.cluster1.LR$expr, by = list(B6.spatial.cluster1.LR$interaction_name), sum)
cluster1.LR.agg$x <- cluster1.LR.agg$x/length(cluster1.LR.agg$Group.1)
B6.spatial.cluster3.LR <- read.table("20210827-figures/figure4/B6-spatial-cluster3-LR.csv", sep = ",", header = T)
cluster3.LR.agg <- aggregate(B6.spatial.cluster3.LR$expr, by = list(B6.spatial.cluster3.LR$interaction_name), sum)
cluster3.LR.agg$x <- cluster3.LR.agg$x/length(cluster3.LR.agg$Group.1)
B6.spatial.cluster6.LR <- read.table("20210827-figures/figure4/B6-spatial-cluster6-LR.csv", sep = ",", header = T)
cluster6.LR.agg <- aggregate(B6.spatial.cluster6.LR$expr, by = list(B6.spatial.cluster6.LR$interaction_name), sum)
cluster6.LR.agg$x <- cluster6.LR.agg$x/length(cluster6.LR.agg$Group.1)
cluster0136.interaction <- Reduce(function(x, y) merge(x, y, by = "Group.1", all = T), 
                                  list(cluster0.LR.agg, cluster1.LR.agg, cluster3.LR.agg, cluster6.LR.agg))
colnames(cluster0136.interaction) <- c("interaction_name", "cluster0", "cluster1", "cluster3", "cluster6")
cluster0136.interaction[is.na(cluster0136.interaction)] <- 0
write.table(cluster0136.interaction, file = "20210827-figures/figure4/cluster0-1-3-6-interaction.csv", sep = ",", col.names = T, row.names = F)
cluster0136.interaction.fc <- read.table("20210827-figures/figure4/cluster0-1-3-6-interaction-FC.csv", sep = ",", header = T)
cluster0136.interaction.fc.1 <- cluster0136.interaction.fc[apply(cluster0136.interaction.fc[, -1], 1, max)>1, ]
cluster0136.interaction.1 <- cluster0136.interaction[cluster0136.interaction$interaction_name %in% cluster0136.interaction.fc.1$interaction_name, ]
cluster0136.interaction.1 <- melt(cluster0136.interaction.1, id.vars = "interaction_name")
ggplot() + 
  geom_bar(cluster0136.interaction.1, mapping = aes(x = value, y = interaction_name, fill = variable), 
           stat = "identity", position = "dodge") + 
  facet_wrap(~ interaction_name, ncol = 10, scales = "free") +
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white"), 
        axis.text.y = element_blank())
```

```{r 比较cluster0，1，3，6中的cell-cell interaction的差别，使用过滤的看一下。其中求均值使用表达这个signal的paires}
B6.spatial.cluster0.LR.f <- read.table("20210827-figures/figure4/B6-spatial-cluster0-LR-filter.csv", sep = ",", header = T)
B6.spatial.cluster0.LR.f.agg <- aggregate(B6.spatial.cluster0.LR.f$value, by = list(B6.spatial.cluster0.LR.f$L_R), mean)
B6.spatial.cluster1.LR.f <- read.table("20210827-figures/figure4/B6-spatial-cluster1-LR-filter.csv", sep = ",", header = T)
B6.spatial.cluster1.LR.f.agg <- aggregate(B6.spatial.cluster1.LR.f$value, by = list(B6.spatial.cluster1.LR.f$L_R), mean)
B6.spatial.cluster3.LR.f <- read.table("20210827-figures/figure4/B6-spatial-cluster3-LR-filter.csv", sep = ",", header = T)
B6.spatial.cluster3.LR.f.agg <- aggregate(B6.spatial.cluster3.LR.f$value, by = list(B6.spatial.cluster3.LR.f$L_R), mean)
B6.spatial.cluster6.LR.f <- read.table("20210827-figures/figure4/B6-spatial-cluster6-LR-filter.csv", sep = ",", header = T)
B6.spatial.cluster6.LR.f.agg <- aggregate(B6.spatial.cluster6.LR.f$value, by = list(B6.spatial.cluster6.LR.f$L_R), mean)
cluster0136.interaction.f <- Reduce(function(x, y) merge(x, y, by = "Group.1", all = T), 
                                  list(B6.spatial.cluster0.LR.f.agg, B6.spatial.cluster1.LR.f.agg, 
                                       B6.spatial.cluster3.LR.f.agg, B6.spatial.cluster6.LR.f.agg))
colnames(cluster0136.interaction.f) <- c("interaction_name", "cluster0", "cluster1", "cluster3", "cluster6")
cluster0136.interaction.f[is.na(cluster0136.interaction.f)] <- 0
cluster0136.interaction.f <- melt(cluster0136.interaction.f, id.vars = "interaction_name")
ggplot() + 
  geom_bar(cluster0136.interaction.f, mapping = aes(x = value, y = interaction_name, fill = variable), 
           stat = "identity", position = "dodge") + 
  facet_wrap(~ interaction_name, ncol = 10, scales = "free") +
  theme(panel.grid = element_blank(), panel.background = element_rect(color = "black", fill = "white"), 
        axis.text.y = element_blank())
```

```{r 比较cluster1，3，6中的cycling DSC的区别}
load("20210818-spatial/B6-bin50-spatial-phago-map.RData")
B6.bin50$cluster_celltype <- paste(B6.bin50$seurat_clusters, B6.bin50$celltype, sep = "_")
DefaultAssay(B6.bin50) <- "SCT"
B6.bin50@active.ident <- factor(B6.bin50$cluster_celltype)
B6.bin50.cycling.DSC <- subset(B6.bin50, subset = cluster_celltype %in% c("1_Top2a-D","3_Top2a-D","6_Top2a-D"))
B6.bin50.cycling.DSC.markers <- FindAllMarkers(B6.bin50.cycling.DSC, min.pct = 0.5, logfc.threshold = 0.5, only.pos = T)
B6.bin50.cycling.DSC <- ScaleData(B6.bin50.cycling.DSC, features = rownames(B6.bin50.cycling.DSC))
pdf("20210827-figures/figure4/Figure4-12-Cycling-DSC-cluster1-3-6-DEGs-heatmap.pdf", width = 10, height = 15)
DoHeatmap(B6.bin50.cycling.DSC, features = B6.bin50.cycling.DSC.markers$gene) + 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 5, name = "RdBu")))
dev.off()
```















